const validCompanies = [
    "A.B.DISTRIBUTOR, SILIGURI ",
    "A.K.DISTRIBUTORS, SILIGURI",
    "AASTHA MEDICA PRADHAN NAGAR 2 NEW, SILIGU",
    "AASTHA MEDICAL (2), SILIGURI",
    "AASTHA MEDICAL (B.J.P), SILIGURI ",
    "AASTHA MEDICAL ..., SILIGURI",
    "AASTHA MEDICAL SALBARI, SILIGURI ",
    "AASTHA MEDICAL s.f, SILIGURI",
    "AASTHA MEDICAL., JAIGOAN",
    "AASTHA MEDICAL^, JALPAIGURI ",
    "ADIGURU SURGIMED SOLUTIONS, SILIGURI ",
    "ANILA DISTRIBUTOR, SILIGURI ",
    "ANNADA DISTRIBUTORS, SILIGURI ",
    "BANSAL BROTHERS, SILIGURI ",
    "BASANT PHARMA AGENCY, SILIGURI",
    "BENGAL MEDICAL STORES PVT LTD, SILIGURI",
    "BENGAL MEDICAL STORES, SILIGURI",
    "BIJOLI MEDICAL AGENCY, ISLAMPUR",
    "CARE -U, SILIGURI",
    "CHARU ENTERPRISE, SILIGURI",
    "CHOUDHURY DRUG DISTRIBUTORS, SILIGURI",
    "CHOWDHURY MEDICAL STORES, JALPAIGURI ",
    "DAS AGENCIES, SILIGURI",
    "DAS ENTERPRISE(JAL), JALPAIGURI",
    "DEEP ENTERPRISE, COOCHBEHAR ",
    "DEEPAK ENTERPRISE, SILIGURI ",
    "DRUGS EMPORIUM, SILIGURI",
    "DUTTA ENTERPRISE., GOALPARA",
    "ESS PEE GEE ENTERPRISE, SILIGURI",
    "G M DISTRIBUTOR, SILIGURI ",
    "GAYATRI MEDICINE TREDERS, MUZAFFARPUR",
    "GHOSH $ COMPANY, SILIGURI ",
    "GHOSH BROTHERS, SILIGURI",
    "GOPAL DRUG AGENCY, SILIGURI ",
    "GORAV ENTERPRISES, SILIGURI ",
    "GUPTA MEDICAL HALL, SILIGURI",
    "GUPTA MEDICINE CENTER, SILIGURI",
    "H.S.MEDICINE DISTRIBUTORS, SILIGURI",
    "HALDIBARI MEDICAL HALL, HALDIRABI",
    "HINDUSTHAN DRUGs, SILIGURI",
    "INDIAN DISTRIBUTOR, SILIGURI",
    "JAI GURU TRADING CO., SILIGURI",
    "JIWAN DRUG DISTRIBUTOR, SILIGURI ",
    "JOY DURGA DISTRIBUTORS, SILIGURI ",
    "JYOSTNA DRUG DISTRIBUTORS, SILIGURI",
    "JYOTI MEDICAL $ GENARAL STORES, SILIGURI ",
    "K.M.C.ENTERPRISE, SILIGURI",
    "KIRAN MEDICO, SILIGURI",
    "LIFE LINE, SILIGURI",
    "M/S HEALTH CURE, JALPAIGURI ",
    "M/S MEDICOSS, SILIGURI",
    "M/S MEDIFARE, JALPAIGURI",
    "M/S MEDIZONE, JALPAIGURI",
    "M/S MEDLIFE, JALPAIGURI ",
    "M/S N J MEDIHUB, SILIGURI ",
    "M/S NEW DEYS MEDICAL, SILIGURI",
    "M/S SWASTIC MEDICAL AGENCY, JALPAIGURI ",
    "MA SANTOSI MEDICAL AGENCY, BAGDOGRA",
    "MAA RENUKA MEDICAL STORE, JALPAIGURI ",
    "MADAN MOHAN DRUGS, KOKRAJHAR",
    "MAHER DISTRIBUTORS, SILIGURI",
    "MALA MEDICAL STORES, DERJEELING",
    "MATRI AGENCY, SILIGURI",
    "MAYA DRUG, ALIPURDUAR ",
    "MEDILIFE .., JALPAIGURI ",
    "MEDIZONE..., HALDIRABI",
    "MILI DRUG AGENCY, SILIGURI",
    "MITRA AGENCY, SILIGURI",
    "MOTHER DRUG DISTRIBUTORS, SILIGURI ",
    "MUKHERJEE & CHOWDHURY BROTHERS, BANARHAT ",
    "NANDI PHARMACEUTICALS, SILIGURI",
    "NETAJI MEDICINE AGENCY, SILIGURI ",
    "NEW ASHIRBAD MEDILIFE, SILIGURI",
    "NEW SANJOY MEDICAL, SILIGURI",
    "NIRMALA MEDICAL STORES, SILIGURI ",
    "OM HIMALAYAN MEDICAL HALL, SIKKIM",
    "P. M.PHARMA, SILIGURI ",
    "PANI MEDICINE DISTRIBUTOR, ALIPURDUAR",
    "PLANET HEALTH, SILIGURI ",
    "RAJMEDICO, SILIGURI ",
    "RAMKRISHNA MEDICINE DISTRIBUTORS, SILIGUR",
    "RIDDHI MEDICAL HALL, SILIGURI ",
    "RUCHI MEDICO, SILIGURI",
    "SAAVI MEDICAL, SILIGURI ",
    "SAHA MEDICAL(), MATHABANGA",
    "SAMPRITI MEDICAL, MATHABANGA",
    "SANCHITA MEDICAL HALL, DERJEELING",
    "SARKAR & SARKAR COMPANY, SILIGURI",
    "SHIB DRUG DISTRIBUTORS, JALPAIGURI ",
    "SHREE SATI DISTRIBUTORS, MALBAZAR",
    "SHREEMA MEDICAL AGENCY, SILIGURI ",
    "SHREYOSI ENTERPRISE, SILIGURI ",
    "SHYAM ENTERPRISES, SILIGURI ",
    "SILIGURI MEDICINE, SILIGURI ",
    "SOURAV MEDICAL AGENCY, SILIGURI",
    "SREE KRISHNA DRUG AGENCY, SILIGURI ",
    "SUN HEALTH, SILIGURI",
    "SUNNY DRUG AGENCY, SILIGURI ",
    "SUPER PHARMA., SILIGURI ",
    "SUROSHI ENTERPRISE, SILIGURI",
    "SURYA ENTERPRISE, SILIGURI",
    "SWASTH MEDICAL, SILIGURI",
    "SWASTH MEDICAL............., SILIGURI",
    "THE NEO PHARMA, SILIGURI",
    "TIRUPATI ENTERPRISE, SILIGURI",
    "UNIQUE DRUG HOUSE, SILIGURI",
    "UNITED DISTRIBUTORS, SILIGURI",
    "URBANSMILE UNITED PVT.LTD, SILIGURI",
    "VANYA HEALTH CARE, SILIGURI",
    "WELLNESS FOREVER, SILIGURI"
    ]

export default function CompanyPicker({value, onChange }) {
    const showDropdown = value.length >= 3;

    return (
        <div className="home-input-fields">
            <input
                type="text"
                placeholder="Company Name"
                value={value}
                onChange={e => onChange(e.target.value)}
                // only hook up the datalist after 3 chars
                list={showDropdown ? "company-list" : undefined}
            />

            {showDropdown && (
                <datalist id="company-list">
                    {validCompanies.map((c, i) => (
                        <option key={i} value={c} />
                    ))}
                </datalist>
            )}
        </div>
    );
}